// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package admin

import (
	"blog/internal/domain/admin/controller"
	"blog/internal/domain/admin/repository"
	"blog/internal/domain/admin/router"
	"blog/internal/domain/admin/service"
	"blog/pkg/repository/db"
	"blog/pkg/repository/redis"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// InitializeAdminAPI 初始化Admin模块的API
func InitV1(r *gin.RouterGroup) error {
	gormDB := db.DB()
	client := redis.Client()
	repositoryRepository := repository.NewRepository(gormDB, client)
	serviceService := service.NewService(repositoryRepository)
	controllerController := controller.NewController(serviceService)
	error2 := router.RegisterV1(r, controllerController)
	return error2
}
