// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package moment

import (
	"blog/internal/domain/moment/controller"
	"blog/internal/domain/moment/infrastructure/cache"
	"blog/internal/domain/moment/infrastructure/db"
	"blog/internal/domain/moment/router"
	"blog/internal/domain/moment/service"
	"blog/pkg/repository"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitV1(r *gin.RouterGroup) error {
	gormDB := repository.GormDB()
	dbDB := db.NewDB(gormDB)
	client := repository.RedisClient()
	cacheCache := cache.NewCache(client)
	serviceService := service.NewService(dbDB, cacheCache)
	controllerController := controller.NewController(serviceService)
	error2 := router.RegisterV1(r, controllerController)
	return error2
}
