// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package friendLink

import (
	"blog/internal/domain/friendLink/controller"
	"blog/internal/domain/friendLink/infrastructure/cache"
	"blog/internal/domain/friendLink/infrastructure/db"
	"blog/internal/domain/friendLink/infrastructure/notifier"
	"blog/internal/domain/friendLink/router"
	"blog/internal/domain/friendLink/service"
	"blog/internal/domain/friendLink/worker"
	"blog/pkg/email"
	"blog/pkg/repository"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitV1(r *gin.RouterGroup) error {
	gormDB := repository.GormDB()
	dbDB := db.NewDB(gormDB)
	client := repository.RedisClient()
	cacheCache := cache.NewCache(client)
	mailer := email.GetMailer()
	notifierNotifier := notifier.NewMailer(mailer)
	serviceService := service.NewService(dbDB, cacheCache, notifierNotifier)
	controllerController := controller.NewController(serviceService)
	error2 := router.RegisterV1(r, controllerController)
	return error2
}

func InitWorker() worker.Worker {
	gormDB := repository.GormDB()
	dbDB := db.NewDB(gormDB)
	mailer := email.GetMailer()
	notifierNotifier := notifier.NewMailer(mailer)
	workerWorker := worker.NewWorker(dbDB, notifierNotifier)
	return workerWorker
}
